### PR TITLE
Delegated Private Matching for Compute (DPMC)

### PR DESCRIPTION
**Pull request by jimouris**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs change / refactoring / dependency upgrade

## Motivation and Context / Related issue

1) Extending multi-key Private-ID to Delegated Private Matching for Compute (DPMC) which supports multiple partners with the help of a helper/delegate server.

* Company has a csv with identifiers (e.g., `etc/example/dpmc/Ex0_company.csv`).
* Partner has a csv with identifiers (e.g., `etc/example/dpmc/Ex0_partner_1.csv`) and a csv with features (e.g., `etc/example/dpmc/Ex0_partner_1_features.csv`).

2) Extending DPMC to Delegated Private Matching for Compute with Secure Shuffling (DSPMC) which supports multiple partners with the help of two helpers/delegate servers.

* Company has a csv with identifiers (e.g., `etc/example/dspmc/Ex0_company.csv`).
* Partner has a csv with identifiers (e.g., `etc/example/dspmc/Ex0_partner_1.csv`) and a csv with features (e.g., `etc/example/dspmc/Ex0_partner_1_features.csv`).

## How Has This Been Tested (if it applies)

Tests are located in `etc/example/dpmc` and `etc/example/dspmc`. 

## Checklist

- [x] The documentation is up-to-date with the changes I made.
- [x] I have read the **CONTRIBUTING** document and completed the CLA (see **CONTRIBUTING**).
- [x] All tests passed, and additional code has been covered with new tests.

### CODE REVIEW

**Review by shubho — APPROVED** [review]

**Comment by shubho** [comment]
Can you why we get
```
unresolved import `aws_sdk_s3::error::NoSuchUpload`
```
consider importing one of these items instead
private_id_protocols/private_id/common/src/s3_path.rs

in lines 13 to 17?

**Comment by jimouris** [comment]
@shubho I updated the AWS crates, it should be fine now. Can you try again?

**Comment by shubho** [comment]
Failed to resolve
```
failed to resolve: use of undeclared crate or module `fernet`
```
in ‎
private_id_protocols‎/private_id‎/protocol‎/src‎/dpmc‎/helper.rs‎
private_id_protocols‎/private_id‎/protocol‎/src‎/dpmc‎/partner.rs‎

**Comment by shubho** [comment]
```
can't find crate for `base64`
```
in 
private_id_protocols‎/private_id‎/protocol‎/src‎/dpmc‎/helper.rs‎
private_id_protocols‎/private_id‎/protocol‎/src‎/dpmc‎/partner.rs‎

**Comment by jimouris** [comment]
@shubho I updated these two crates to their latest versions. Their API had changed a bit. Let's see if that was the issue.

**Comment by shubho** [comment]
I still get the same errors - the `fernet` errors are in 
line 113 and 174 `private_id/protocol/src/dpmc/helper.rs`
line 182 and 285 `private_id/protocol/src/dpmc/partner.rs`

And the `base64` errors are in
line 4 in `private_id/protocol/src/dpmc/helper.rs`
line 4 in `private_id/protocol/src/dpmc/partner.rs`

**Comment by jimouris** [comment]
I made some changes, can you check again? What is the command that generates these errors? I can't replicate them locally.

**Comment by shubho** [comment]
Same problem when you do `use base64` or `use fernet` they aren't resolving - do you need to do `extern`? The lines where you do `use base64` (or `fernet`) - I get `unresolved import base64` etc

**Comment by jimouris** [comment]
That's odd, both dependencies are in [Cargo.toml](https://github.com/jimouris/delegated-private-matching-for-compute/blob/main/protocol/Cargo.toml) and I have `use` statements. Based on [this](https://stackoverflow.com/questions/29403920/whats-the-difference-between-use-and-extern-crate) `use` should be sufficient. I had it with `extern crate ..` before and it was also causing the error.

Is there a way to find the specific Rust version and the command that generates the error?

**Comment by shubho** [comment]
I think the problem is the `base64` and `fernet` packages don't exist in our internal build system - this will take longer than expected I think

**Comment by jimouris** [comment]
I see, I changed the way we're pulling them in Cargo.toml. Now, we're pulling them from GitHub directly so this might solve the issue. Can you try again?

**Comment by prasadbuddhavarapu** [comment]
Updated fernet, and base64 should be 0.13. We should do another pull to update.

**Pull request closed without merging**
